import { Cemetery } from './cemetery';

export const CEMETERYS: Cemetery[] = [
    {
        id: 9,
        name: "Воронино",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1078789,
        name: "Воронинское кладбище города Томска",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[
            "/assets/images/img.jpg",
            "/assets/images/img1.jpg",
            "/assets/images/img2.jpg",
            "/assets/images/img3.jpg",
            "/assets/images/img4.jpg",
            "/assets/images/img5.jpg",
            "/assets/images/img6.jpg",
            "/assets/images/img7.jpg",
            "/assets/images/img8.jpg",
            "/assets/images/img9.jpg",
            "/assets/images/img10.jpg",
            "/assets/images/img11.jpg",
            "/assets/images/img12.jpg",
        ]
    },
    {
        id: 11375,
        name: "Воронинское кладбище города Томска - 1",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[
            "/assets/images/img.jpg",
            "/assets/images/img1.jpg",
            "/assets/images/img2.jpg",
            "/assets/images/img3.jpg",
            "/assets/images/img4.jpg",
            "/assets/images/img5.jpg",
            "/assets/images/img6.jpg",
            "/assets/images/img7.jpg",
            "/assets/images/img8.jpg",
            "/assets/images/img9.jpg",
            "/assets/images/img10.jpg",
            "/assets/images/img11.jpg",
            "/assets/images/img12.jpg",
        ]
                },
    {
        id: 186782,
        name: "Воронинское кладбище города Томска - 2",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 178783,
        name: "Воронинское кладбище города Томска - 3",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 898914,
        name: "Воронинское кладбище города Томска - 4",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 189895,
        name: "Воронинское кладбище города Томска - 5",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 7899,
        name: "Воронино",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 10121,
        name: "Воронинское кладбище города Томска",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 11211,
        name: "Воронинское кладбище города Томска - 1",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 112122,
        name: "Воронинское кладбище города Томска - 2",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 11213,
        name: "Воронинское кладбище города Томска - 3",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1400,
        name: "Воронинское кладбище города Томска - 4",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1500,
        name: "Воронинское кладбище города Томска - 5",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 9000,
        name: "Воронино",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 100000,
        name: "Воронинское кладбище города Томска",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 112222,
        name: "Воронинское кладбище города Томска - 1",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 111112,
        name: "Воронинское кладбище города Томска - 2",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 131111,
        name: "Воронинское кладбище города Томска - 3",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 141111,
        name: "Воронинское кладбище города Томска - 4",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 15111,
        name: "Воронинское кладбище города Томска - 5",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 9111,
        name: "Воронино",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1011111,
        name: "Воронинское кладбище города Томска",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1122222222222222111,
        name: "Воронинское кладбище города Томска - 1",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 12222222222222,
        name: "Воронинское кладбище города Томска - 2",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 134042,
        name: "Воронинское кладбище города Томска - 3",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 144204,
        name: "Воронинское кладбище города Томска - 4",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 154204,
        name: "Воронинское кладбище города Томска - 5",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 9420420,
        name: "Воронино",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1004045,
        name: "Воронинское кладбище города Томска",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 117837837,
        name: "Воронинское кладбище города Томска - 1",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 12783783,
        name: "Воронинское кладбище города Томска - 2",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1378378,
        name: "Воронинское кладбище города Томска - 3",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1478637,
        name: "Воронинское кладбище города Томска - 4",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 157867,
        name: "Воронинское кладбище города Томска - 5",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 988888,
        name: "Воронино",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 108888,
        name: "Воронинское кладбище города Томска",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 118888,
        name: "Воронинское кладбище города Томска - 1",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 128888,
        name: "Воронинское кладбище города Томска - 2",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 138888,
        name: "Воронинское кладбище города Томска - 3",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1495,
        name: "Воронинское кладбище города Томска - 4",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1595,
        name: "Воронинское кладбище города Томска - 5",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 995,
        name: "Воронино",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1095,
        name: "Воронинское кладбище города Томска",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1159,
        name: "Воронинское кладбище города Томска - 1",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1259,
        name: "Воронинское кладбище города Томска - 2",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1359,
        name: "Воронинское кладбище города Томска - 3",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1459,
        name: "Воронинское кладбище города Томска - 4",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1559,
        name: "Воронинское кладбище города Томска - 5",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 959,
        name: "Воронино",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1030,
        name: "Воронинское кладбище города Томска",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1130,
        name: "Воронинское кладбище города Томска - 1",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1230,
        name: "Воронинское кладбище города Томска - 2",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1330,
        name: "Воронинское кладбище города Томска - 3",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1014,
        name: "Воронинское кладбище города Томска - 4",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1015,
        name: "Воронинское кладбище города Томска - 5",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id:109,
        name: "Воронино",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1100,
        name: "Воронинское кладбище города Томска",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 1011,
        name: "Воронинское кладбище города Томска - 1",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 2012,
        name: "Воронинское кладбище города Томска - 2",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 2013,
        name: "Воронинское кладбище города Томска - 3",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 2014,
        name: "Воронинское кладбище города Томска - 4",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 2015,
        name: "Воронинское кладбище города Томска - 5",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 209,
        name: "Воронино",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 9910,
        name: "Воронинское кладбище города Томска",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 9911,
        name: "Воронинское кладбище города Томска - 1",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 9912,
        name: "Воронинское кладбище города Томска - 2",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 9913,
        name: "Воронинское кладбище города Томска - 3",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 9914,
        name: "Воронинское кладбище города Томска - 4",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 95,
        name: "Воронинское кладбище города Томска - 5",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 99,
        name: "Воронино",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 70,
        name: "Воронинское кладбище города Томска",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 71,
        name: "Воронинское кладбище города Томска - 1",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 72,
        name: "Воронинское кладбище города Томска - 2",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 78,
        name: "Воронинское кладбище города Томска - 3",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 875,
        name: "Воронинское кладбище города Томска - 4",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    },
    {
        id: 19,
        name: "Воронинское кладбище города Томска - 5",
        address: "перекрёсток ул. Карла Маркса и пер. 1905 года",
        sectors: 5,
        places: 451,
        burials: 5555,
        unidentifiable: 1956,
        area: 4.5,
        imgs:[             "/assets/images/img.jpg",             "/assets/images/img1.jpg",             "/assets/images/img2.jpg",             "/assets/images/img3.jpg",             "/assets/images/img4.jpg",             "/assets/images/img5.jpg",             "/assets/images/img6.jpg",             "/assets/images/img7.jpg",             "/assets/images/img8.jpg",             "/assets/images/img9.jpg",             "/assets/images/img10.jpg",             "/assets/images/img11.jpg",             "/assets/images/img12.jpg",         ]
    }
];